FROM busybox:latest

# Create a non-root user to own the files and run our server
RUN adduser -D static
USER static
WORKDIR /home/static

# Run BusyBox httpd - we expect /src-live to be mounted
CMD ["busybox", "httpd", "-f", "-v", "-p", "3000", "-h", "/src-live"]
